### ISSUE TITLE
Problem with A.I keep geting stuck+spawning near/in environment

### ISSUE THREAD

**Issue by B1acKWo1F** [SkaceKamen/random-infantry-skirmish#25]
Thank for Great Scenario but there are few things that gave me a headache
1:  Altis > A.I keep Spawning in Rock and getting stuck forever 
2: Chernarus  > Combat zone near the wood make Vehicles Spawning get stuck in the wood and A.I won't drive out or redeploy and just be stuck there forever
3: Chernarus > Bad Pathfinding Map relates or that just ArmA A.I being Arma A.I or else but most of the time clearly see it in Urban Area A.I keep running their Vehicles into the wall/house/tree ( pretty much everything map relate that can't be a pushover by A.I Vehicles )
4: A.I Vehicles just sitting at Spawn and do nothing ( a system to auto redeploy is a Unit don't do anything after a set amount of time will work just fine )
5:  Chernarus > A.I spawning in Water most notice when attacking Port city in
a system to help fix/prevent those would be great (  i ran the Scenario with LAMBS A.I and DCO Vehicle.FSM )
6: ( Mods relate i guess ) so i like playing with Project injury Reaction (PiR) mod but sometime when you get killed the screen become so blurrrr that lead to unplayerable and force restart is the only way out
i play the Scenario 4-5 round pretty much every night after work so i can playtest here my Steam ID is you want to contract: https://steamcommunity.com/id/Wolf999
p/s: first time using Github and not a native speaker so sorry for my bad English is there anything wrong

**Comment by SkaceKamen** [comment]
Hey, thanks for reporting the issues
For 1,2 and 4, I've implemented a check that should de-spawn the vehicle if it's stuck and not moving for more than 1 minute after spawning:
https://github.com/SkaceKamen/random-infantry-skirmish/blob/master/fnc/all/fn_attachVehicleRefundCheck.sqf

For 3 is a bit harder, it's harder to check if the AI stuck or just not interested in moving, I think that implementing similar check that would despawn the vehicle when not moving for more than 1 minute at any time would be too disruptive.

For 5, it's sometimes hard to find proper spawn spot for some places, I've upgraded the algorithm a bit but it'll still fail sometimes. I'll probably need a different approach for spawning for this to work properly, like moving the spawn point a bit closer to the target until spawning is possible...

And for 6, I'll try to install the mentioned mod, but I'm not sure if I'll be able to fix the compatibility, since it's closed-source.
