### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by carlstery** [SkaceKamen/random-infantry-skirmish#57]
Im getting a average of 30 to 20 fps every time i play with this mod. I have even downloaded mods such as "automatic view distance" and so on. If there was a possible fix to my problem i would greatly appriciate it, because the mod itself is awesome but the fps needs some serious improvements.

**Comment by SkaceKamen** [comment]
I've went through most of the mission code and there shouldn't be anything that'd affect the performance of the game in the mission scripts.
I'll do some profiling to confirm this later, but I'd say the issue is mainly about the fact that there's always (by default) 40+ AIs in the game which could be demanding on some machines.

**Comment by SkaceKamen** [comment]
Performance was improved a bit
